name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim: [v0.10.4, stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.neovim }}
          neovim: true
      - run: make test
      - run: make validate-templates
